import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { formatPrice } from '../lib/format-utils';
import {
  generateGiftCardCode,
  isValidCodeFormat,
  getDefaultExpiry,
  isExpired,
  createWelcomeGiftCard,
  createPromotionalGiftCard,
  createReferralGiftCard,
  createGiftCardAfterPayment,
  REFERRAL_DISCOUNT_AMOUNT,
} from '../lib/giftcard';

// =============================================
// generateGiftCardCode
// =============================================
describe('generateGiftCardCode', () => {
  it('returns a code in FWGC-XXXX-XXXX-XXXX format', () => {
    const code = generateGiftCardCode();
    expect(code).toMatch(/^FWGC-[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}$/);
  });

  it('starts with FWGC- prefix', () => {
    const code = generateGiftCardCode();
    expect(code.startsWith('FWGC-')).toBe(true);
  });

  it('has 4 segments separated by hyphens', () => {
    const code = generateGiftCardCode();
    const segments = code.split('-');
    expect(segments).toHaveLength(4);
    expect(segments[0]).toBe('FWGC');
    expect(segments[1]).toHaveLength(4);
    expect(segments[2]).toHaveLength(4);
    expect(segments[3]).toHaveLength(4);
  });

  it('excludes confusing characters (0, O, 1, I)', () => {
    // Generate many codes to ensure we never see excluded chars
    for (let i = 0; i < 100; i++) {
      const code = generateGiftCardCode();
      const body = code.replace('FWGC-', '').replace(/-/g, '');
      expect(body).not.toContain('0');
      expect(body).not.toContain('O');
      expect(body).not.toContain('1');
      expect(body).not.toContain('I');
    }
  });

  it('generates unique codes', () => {
    const codes = new Set<string>();
    for (let i = 0; i < 200; i++) {
      codes.add(generateGiftCardCode());
    }
    // With cryptographic randomness and 30^12 possibilities, all should be unique
    expect(codes.size).toBe(200);
  });

  it('only contains uppercase letters and digits in code body', () => {
    for (let i = 0; i < 50; i++) {
      const code = generateGiftCardCode();
      const body = code.replace('FWGC-', '').replace(/-/g, '');
      expect(body).toMatch(/^[A-Z2-9]+$/);
    }
  });
});

// =============================================
// isValidCodeFormat (validateGiftCardCode)
// =============================================
describe('isValidCodeFormat', () => {
  it('accepts valid format FWGC-XXXX-XXXX-XXXX', () => {
    expect(isValidCodeFormat('FWGC-ABCD-EFGH-JKLM')).toBe(true);
  });

  it('accepts codes with allowed digits 2-9', () => {
    expect(isValidCodeFormat('FWGC-2345-6789-ABCD')).toBe(true);
  });

  it('rejects codes with 0 (excluded char)', () => {
    expect(isValidCodeFormat('FWGC-A0CD-EFGH-JKLM')).toBe(false);
  });

  it('rejects codes with 1 (excluded char)', () => {
    expect(isValidCodeFormat('FWGC-A1CD-EFGH-JKLM')).toBe(false);
  });

  it('rejects codes with O (excluded char)', () => {
    expect(isValidCodeFormat('FWGC-AOCD-EFGH-JKLM')).toBe(false);
  });

  it('rejects codes with I (excluded char)', () => {
    expect(isValidCodeFormat('FWGC-AICD-EFGH-JKLM')).toBe(false);
  });

  it('normalizes lowercase to uppercase before validation', () => {
    expect(isValidCodeFormat('fwgc-abcd-efgh-jklm')).toBe(true);
  });

  it('normalizes mixed case', () => {
    expect(isValidCodeFormat('Fwgc-AbCd-EfGh-JkLm')).toBe(true);
  });

  it('trims whitespace', () => {
    expect(isValidCodeFormat('  FWGC-ABCD-EFGH-JKLM  ')).toBe(true);
  });

  it('rejects wrong prefix', () => {
    expect(isValidCodeFormat('GIFT-ABCD-EFGH-JKLM')).toBe(false);
  });

  it('rejects too few segments', () => {
    expect(isValidCodeFormat('FWGC-ABCD-EFGH')).toBe(false);
  });

  it('rejects too many segments', () => {
    expect(isValidCodeFormat('FWGC-ABCD-EFGH-JKLM-NPQR')).toBe(false);
  });

  it('rejects segments with wrong length', () => {
    expect(isValidCodeFormat('FWGC-ABC-EFGH-JKLM')).toBe(false);
    expect(isValidCodeFormat('FWGC-ABCDE-EFGH-JKLM')).toBe(false);
  });

  it('rejects empty string', () => {
    expect(isValidCodeFormat('')).toBe(false);
  });

  it('rejects random string', () => {
    expect(isValidCodeFormat('not-a-gift-card-code')).toBe(false);
  });

  it('validates codes generated by generateGiftCardCode', () => {
    for (let i = 0; i < 50; i++) {
      const code = generateGiftCardCode();
      expect(isValidCodeFormat(code)).toBe(true);
    }
  });
});

// =============================================
// formatPrice (formerly formatGBP)
// =============================================
describe('formatPrice', () => {
  it('formats integer amount', () => {
    expect(formatPrice(50)).toBe('\u00a350.00');
  });

  it('formats decimal amount', () => {
    expect(formatPrice(9.99)).toBe('\u00a39.99');
  });

  it('formats zero', () => {
    expect(formatPrice(0)).toBe('\u00a30.00');
  });

  it('rounds to 2 decimal places', () => {
    expect(formatPrice(19.999)).toBe('\u00a320.00');
  });

  it('formats large amounts', () => {
    expect(formatPrice(1000)).toBe('\u00a31000.00');
  });
});

// =============================================
// getDefaultExpiry
// =============================================
describe('getDefaultExpiry', () => {
  it('returns a valid ISO date string', () => {
    const expiry = getDefaultExpiry();
    expect(() => new Date(expiry)).not.toThrow();
    expect(new Date(expiry).toISOString()).toBe(expiry);
  });

  it('returns a date approximately 1 year from now', () => {
    const now = new Date();
    const expiry = new Date(getDefaultExpiry());
    const diffMs = expiry.getTime() - now.getTime();
    const diffDays = diffMs / (1000 * 60 * 60 * 24);
    // Should be between 364 and 367 days (accounting for leap years and timing)
    expect(diffDays).toBeGreaterThan(363);
    expect(diffDays).toBeLessThan(368);
  });
});

// =============================================
// isExpired
// =============================================
describe('isExpired', () => {
  it('returns false for null expiresAt (no expiry)', () => {
    expect(isExpired(null)).toBe(false);
  });

  it('returns false for future date', () => {
    const future = new Date();
    future.setFullYear(future.getFullYear() + 1);
    expect(isExpired(future.toISOString())).toBe(false);
  });

  it('returns true for past date', () => {
    const past = new Date();
    past.setFullYear(past.getFullYear() - 1);
    expect(isExpired(past.toISOString())).toBe(true);
  });
});

// =============================================
// createWelcomeGiftCard
// =============================================
describe('createWelcomeGiftCard', () => {
  it('creates a gift card with correct defaults', () => {
    const gc = createWelcomeGiftCard('test@example.com');
    expect(gc.originalValue).toBe(50);
    expect(gc.currentBalance).toBe(50);
    expect(gc.type).toBe('welcome');
    expect(gc.isActive).toBe(true);
    expect(gc.redeemedBy).toBeNull();
    expect(gc.redeemedAt).toBeNull();
    expect(gc.createdFor).toBe('test@example.com');
  });

  it('generates a valid gift card code', () => {
    const gc = createWelcomeGiftCard();
    expect(isValidCodeFormat(gc.code)).toBe(true);
  });

  it('sets description mentioning welcome and amount', () => {
    const gc = createWelcomeGiftCard();
    expect(gc.description).toContain('50');
    expect(gc.description).toContain('Welcome');
  });

  it('sets expiry date approximately 1 year from now', () => {
    const gc = createWelcomeGiftCard();
    expect(gc.expiresAt).toBeTruthy();
    const expiry = new Date(gc.expiresAt!);
    const diffDays = (expiry.getTime() - Date.now()) / (1000 * 60 * 60 * 24);
    expect(diffDays).toBeGreaterThan(363);
  });

  it('sets createdAt to current time', () => {
    const before = Date.now();
    const gc = createWelcomeGiftCard();
    const after = Date.now();
    const created = new Date(gc.createdAt).getTime();
    expect(created).toBeGreaterThanOrEqual(before);
    expect(created).toBeLessThanOrEqual(after);
  });
});

// =============================================
// createPromotionalGiftCard
// =============================================
describe('createPromotionalGiftCard', () => {
  it('creates a gift card with specified value', () => {
    const gc = createPromotionalGiftCard(25, 'Summer sale promo', 'user@example.com');
    expect(gc.originalValue).toBe(25);
    expect(gc.currentBalance).toBe(25);
    expect(gc.type).toBe('promotional');
    expect(gc.description).toBe('Summer sale promo');
    expect(gc.createdFor).toBe('user@example.com');
  });

  it('generates a valid code', () => {
    const gc = createPromotionalGiftCard(10, 'Test');
    expect(isValidCodeFormat(gc.code)).toBe(true);
  });

  it('createdFor is optional', () => {
    const gc = createPromotionalGiftCard(10, 'Test');
    expect(gc.createdFor).toBeUndefined();
  });
});

// =============================================
// createReferralGiftCard
// =============================================
describe('createReferralGiftCard', () => {
  it('creates a referral gift card with correct discount amount', () => {
    const gc = createReferralGiftCard('user123', 'DJ Fresh');
    expect(gc.originalValue).toBe(REFERRAL_DISCOUNT_AMOUNT);
    expect(gc.currentBalance).toBe(REFERRAL_DISCOUNT_AMOUNT);
    expect(gc.type).toBe('referral');
    expect(gc.restrictedTo).toBe('pro_upgrade');
    expect(gc.createdByUserId).toBe('user123');
  });

  it('includes referrer name in description when provided', () => {
    const gc = createReferralGiftCard('user123', 'DJ Fresh');
    expect(gc.description).toContain('DJ Fresh');
    expect(gc.description).toContain('Pro upgrade');
  });

  it('uses generic description when referrer name is not provided', () => {
    const gc = createReferralGiftCard('user123');
    expect(gc.description).toContain('referral');
    expect(gc.description).toContain('Pro upgrade');
  });

  it('generates valid code', () => {
    const gc = createReferralGiftCard('user123');
    expect(isValidCodeFormat(gc.code)).toBe(true);
  });

  it('REFERRAL_DISCOUNT_AMOUNT is 5', () => {
    expect(REFERRAL_DISCOUNT_AMOUNT).toBe(5);
  });
});

// =============================================
// createGiftCardAfterPayment
// =============================================
describe('createGiftCardAfterPayment', () => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let mockFirebaseOps: any;

  let originalFetch: typeof globalThis.fetch;
  let mockFetch: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    mockFirebaseOps = {
      queryCollection: vi.fn().mockResolvedValue([]), // no existing codes
      addDocument: vi.fn().mockResolvedValue({ id: 'gc_123' }),
      updateDocument: vi.fn().mockResolvedValue(undefined),
      getDocument: vi.fn().mockResolvedValue(null),
    };

    originalFetch = globalThis.fetch;
    mockFetch = vi.fn();
    globalThis.fetch = mockFetch as typeof globalThis.fetch;

    // Mock the purchase record subcollection write
    mockFetch.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({}),
      text: () => Promise.resolve(''),
    });
  });

  afterEach(() => {
    globalThis.fetch = originalFetch;
  });

  it('creates a gift card successfully for a gift purchase', async () => {
    const data = {
      amount: 25,
      buyerUserId: 'buyer123',
      buyerEmail: 'buyer@example.com',
      buyerName: 'Test Buyer',
      recipientType: 'gift' as const,
      recipientName: 'Recipient',
      recipientEmail: 'recipient@example.com',
      message: 'Happy birthday!',
      paymentIntentId: 'pi_123',
    };

    const result = await createGiftCardAfterPayment(data, mockFirebaseOps);

    expect(result.success).toBe(true);
    expect(result.giftCard).toBeDefined();
    expect(result.giftCard!.amount).toBe(25);
    expect(result.giftCard!.recipientEmail).toBe('recipient@example.com');
    expect(result.giftCard!.code).toBeTruthy();
    expect(isValidCodeFormat(result.giftCard!.code)).toBe(true);
  });

  it('creates a self-purchase gift card', async () => {
    const data = {
      amount: 50,
      buyerUserId: 'buyer123',
      buyerEmail: 'buyer@example.com',
      buyerName: 'Self Buyer',
      recipientType: 'self' as const,
      recipientName: 'Self Buyer',
      recipientEmail: 'buyer@example.com',
      message: '',
    };

    const result = await createGiftCardAfterPayment(data, mockFirebaseOps);

    expect(result.success).toBe(true);
    expect(result.giftCard!.recipientEmail).toBe('buyer@example.com');
  });

  it('generates unique code by retrying on collision', async () => {
    // First query returns existing code, subsequent queries return empty
    mockFirebaseOps.queryCollection
      .mockResolvedValueOnce([{ code: 'EXISTING' }]) // collision
      .mockResolvedValueOnce([{ code: 'EXISTING2' }]) // collision again
      .mockResolvedValueOnce([]); // unique

    const data = {
      amount: 10,
      buyerUserId: 'buyer123',
      buyerEmail: 'buyer@example.com',
      buyerName: 'Test',
      recipientType: 'self' as const,
      recipientName: 'Test',
      recipientEmail: 'buyer@example.com',
      message: '',
    };

    const result = await createGiftCardAfterPayment(data, mockFirebaseOps);
    expect(result.success).toBe(true);
    // queryCollection should have been called 3 times for code uniqueness
    expect(mockFirebaseOps.queryCollection).toHaveBeenCalledTimes(3);
  });

  it('stores gift card document in Firestore', async () => {
    const data = {
      amount: 30,
      buyerUserId: 'buyer123',
      buyerEmail: 'buyer@example.com',
      buyerName: 'Buyer',
      recipientType: 'gift' as const,
      recipientName: 'Recipient',
      recipientEmail: 'recipient@example.com',
      message: 'Enjoy!',
      paymentIntentId: 'pi_abc',
    };

    await createGiftCardAfterPayment(data, mockFirebaseOps);

    expect(mockFirebaseOps.addDocument).toHaveBeenCalledWith(
      'giftCards',
      expect.objectContaining({
        originalValue: 30,
        currentBalance: 30,
        isActive: true,
        recipientEmail: 'recipient@example.com',
        purchasedBy: 'buyer123',
        paymentIntentId: 'pi_abc',
      })
    );
  });

  it('looks up buyer name from user doc when not provided', async () => {
    mockFirebaseOps.getDocument.mockResolvedValueOnce({
      displayName: 'DB User Name',
    });

    const data = {
      amount: 15,
      buyerUserId: 'buyer123',
      buyerEmail: 'buyer@example.com',
      buyerName: '', // empty - should look up from DB
      recipientType: 'self' as const,
      recipientName: 'Self',
      recipientEmail: 'buyer@example.com',
      message: '',
    };

    await createGiftCardAfterPayment(data, mockFirebaseOps);

    expect(mockFirebaseOps.getDocument).toHaveBeenCalledWith('users', 'buyer123');
  });

  it('returns error on failure', async () => {
    mockFirebaseOps.addDocument.mockRejectedValueOnce(new Error('DB error'));

    const data = {
      amount: 10,
      buyerUserId: 'buyer123',
      buyerEmail: 'buyer@example.com',
      buyerName: 'Test',
      recipientType: 'self' as const,
      recipientName: 'Test',
      recipientEmail: 'buyer@example.com',
      message: '',
    };

    const result = await createGiftCardAfterPayment(data, mockFirebaseOps);
    expect(result.success).toBe(false);
    expect(result.error).toBeDefined();
  });

  it('handles PayPal order ID', async () => {
    const data = {
      amount: 20,
      buyerUserId: 'buyer123',
      buyerEmail: 'buyer@example.com',
      buyerName: 'Buyer',
      recipientType: 'self' as const,
      recipientName: 'Buyer',
      recipientEmail: 'buyer@example.com',
      message: '',
      paypalOrderId: 'PAYPAL-ORDER-123',
    };

    await createGiftCardAfterPayment(data, mockFirebaseOps);

    expect(mockFirebaseOps.addDocument).toHaveBeenCalledWith(
      'giftCards',
      expect.objectContaining({
        paypalOrderId: 'PAYPAL-ORDER-123',
        paymentIntentId: null, // should be null when not provided
      })
    );
  });
});
