// Admin: grant a user Plus tier directly + trigger the welcome email.
// Bypasses Stripe entirely. Mirrors the data shape from
// stripe-webhook/subscription-helpers.ts so the rest of the system treats
// the user as a normal Plus subscriber.
//
// Usage: node scripts/grant-plus.cjs <uid> <email> [name]
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

function loadEnv() {
  const envPath = path.resolve(__dirname, '..', '.env');
  for (const raw of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('='); if (eq < 0) continue;
    const k = line.slice(0, eq).trim();
    let v = line.slice(eq + 1).trim();
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
    if (!process.env[k]) process.env[k] = v;
  }
}
loadEnv();

const uid = process.argv[2];
const email = process.argv[3];
const name = process.argv[4] || (email ? email.split('@')[0] : 'Plus member');

if (!uid || !email) {
  console.error('usage: node scripts/grant-plus.cjs <uid> <email> [name]');
  process.exit(1);
}

const PROJECT_ID = process.env.FIREBASE_PROJECT_ID || 'freshwax-store';
const PRIVATE_KEY = (process.env.FIREBASE_PRIVATE_KEY || '').replace(/\\n/g, '\n');
const CLIENT_EMAIL = process.env.FIREBASE_CLIENT_EMAIL;
const ADMIN_KEY = process.env.ADMIN_KEY;
const SITE_URL = process.env.SITE_URL || 'https://freshwax.co.uk';

function b64u(s) { return Buffer.from(s).toString('base64').replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_'); }

async function getToken() {
  const now = Math.floor(Date.now() / 1000);
  const head = b64u(JSON.stringify({ alg: 'RS256', typ: 'JWT' }));
  const body = b64u(JSON.stringify({
    iss: CLIENT_EMAIL,
    scope: 'https://www.googleapis.com/auth/datastore',
    aud: 'https://oauth2.googleapis.com/token',
    iat: now,
    exp: now + 3600,
  }));
  const sig = crypto.createSign('RSA-SHA256').update(`${head}.${body}`).sign(PRIVATE_KEY).toString('base64').replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
  const r = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer', assertion: `${head}.${body}.${sig}` }),
  });
  const j = await r.json();
  if (!j.access_token) throw new Error('Token error: ' + JSON.stringify(j));
  return j.access_token;
}

(async () => {
  const token = await getToken();

  // Match the format generated by generatePlusId() in stripe-webhook/subscription-helpers.ts
  const now = new Date();
  const year = now.getFullYear().toString().slice(-2);
  const month = (now.getMonth() + 1).toString().padStart(2, '0');
  const userHash = uid.slice(-4).toUpperCase();
  const plusId = `FWP-${year}${month}-${userHash}`;

  const subscribedAt = now.toISOString();
  const expiresAt = new Date(now.getTime() + 365 * 24 * 60 * 60 * 1000).toISOString();
  const subscriptionId = `admin-grant-${Date.now()}`;

  // Patch only the subscription field via Firestore REST.
  console.log(`Granting Plus to uid=${uid}`);
  console.log(`  plusId=${plusId}`);
  console.log(`  subscribedAt=${subscribedAt}`);
  console.log(`  expiresAt=${expiresAt}`);

  const updateUrl =
    `https://firestore.googleapis.com/v1/projects/${PROJECT_ID}/databases/(default)/documents/users/${uid}` +
    `?updateMask.fieldPaths=subscription&updateMask.fieldPaths=updatedAt`;
  const fsRes = await fetch(updateUrl, {
    method: 'PATCH',
    headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      fields: {
        subscription: {
          mapValue: {
            fields: {
              tier: { stringValue: 'pro' },
              subscribedAt: { stringValue: subscribedAt },
              expiresAt: { stringValue: expiresAt },
              subscriptionId: { stringValue: subscriptionId },
              plusId: { stringValue: plusId },
              paymentMethod: { stringValue: 'admin' },
            },
          },
        },
        updatedAt: { timestampValue: subscribedAt },
      },
    }),
  });
  if (!fsRes.ok) {
    const err = await fsRes.text();
    console.error('Firestore update failed:', fsRes.status, err);
    process.exit(1);
  }
  console.log('  Firestore subscription field set.\n');

  // Send the welcome email through the same admin endpoint Stripe webhooks
  // hit — keeps the email template + delivery path consistent.
  if (!ADMIN_KEY) {
    console.warn('ADMIN_KEY env var not set — skipping welcome email send.');
    console.log('Run separately: POST /api/admin/send-plus-welcome-email/ with X-Admin-Key + { email, name, subscribedAt, expiresAt, plusId }');
    return;
  }

  console.log(`Sending welcome email to ${email}...`);
  const emailRes = await fetch(`${SITE_URL}/api/admin/send-plus-welcome-email/`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-Admin-Key': ADMIN_KEY },
    body: JSON.stringify({ email, name, subscribedAt, expiresAt, plusId, isRenewal: false }),
  });
  const emailBody = await emailRes.text();
  if (!emailRes.ok) {
    console.error('Welcome email send failed:', emailRes.status, emailBody);
    process.exit(1);
  }
  console.log('  Email API ok:', emailBody);
  console.log('\nDone. User should hard-refresh to see Plus features unlocked.');
})().catch((e) => {
  console.error('FATAL:', e);
  process.exit(1);
});
